# Generated by Django 5.2 on 2026-10-10 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0003_tienda_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('separado', 'Separado'), ('abono', 'Abono'), ('cierre', 'Cierre de caja'), ('devolucion', 'Devolución'), ('reporte', 'Reporte'), ('inventario', 'Inventario'), ('compra', 'Orden de compra'), ('recepcion', 'Recepción')], max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('contenido', models.BinaryField()),
                ('size_kb', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to=settings.AUTH_USER_MODEL)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='tiendas.tienda')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
