# Generated by Django 5.1.7 on 2026-03-26 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_alter_sesioncaja_id'),
        ('productos', '0002_alter_categoria_id_alter_inventario_id_and_more'),
        ('tiendas', '0002_alter_tienda_id'),
        ('ventas', '0002_alter_detalledevolucion_id_alter_detalleventa_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucion',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='venta',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='descuento',
            new_name='descuento_total',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='impuestos',
            new_name='impuesto_total',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='monto_pagado',
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('completada', 'Completada'), ('anulada', 'Anulada')], default='completada', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='sesion_caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='caja.sesioncaja'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='tiendas.tienda'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table=None,
        ),
        migrations.AlterModelTable(
            name='venta',
            table=None,
        ),
        migrations.DeleteModel(
            name='DetalleDevolucion',
        ),
        migrations.DeleteModel(
            name='Devolucion',
        ),
    ]
