# Generated by Django 5.1.7 on 2026-04-17 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_movimientocaja'),
        ('clientes', '0003_cliente_empresa'),
        ('tiendas', '0003_tienda_empresa'),
        ('ventas', '0003_remove_devolucion_empleado_remove_devolucion_venta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('nota_credito', 'Nota Crédito'), ('devolucion', 'Reconocimiento por devolución')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['tienda', '-created_at'], name='ventas_vent_tienda__142115_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['sesion_caja'], name='ventas_vent_sesion__b09438_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado'], name='ventas_vent_estado_b0d674_idx'),
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta'),
        ),
        migrations.AddIndex(
            model_name='pagoventa',
            index=models.Index(fields=['venta'], name='ventas_pago_venta_i_dc4d25_idx'),
        ),
    ]
