# Generated by Django 5.1.7 on 2026-06-05 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_movimientocaja'),
        ('clientes', '0006_alter_cliente_apellido_alter_cliente_cedula_nit_and_more'),
        ('empresas', '0002_empresa_cantidad_mayoreo_empresa_maneja_mayoreo'),
        ('tiendas', '0003_tienda_empresa'),
        ('ventas', '0004_pagoventa_venta_ventas_vent_tienda__142115_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='venta',
            name='ventas_vent_tienda__142115_idx',
        ),
        migrations.AddField(
            model_name='venta',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='empresas.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa', 'tienda', '-created_at'], name='ventas_vent_empresa_938530_idx'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_factura'), name='venta_empresa_numero_factura_uniq'),
        ),
    ]
