# Generated by Django 5.1.7 on 2026-06-05 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_cantidad_mayoreo_empresa_maneja_mayoreo'),
        ('ventas', '0005_remove_venta_ventas_vent_tienda__142115_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consecutivo_factura', to='empresas.empresa')),
            ],
        ),
    ]
