# Generated by Django 5.2 on 2026-07-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_detalleventa_costo_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='a_credito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto'), ('credito', 'Crédito')], default='efectivo', max_length=20),
        ),
    ]
