# Generated by Django 5.2 on 2026-06-26 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0003_tienda_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_papel', models.CharField(choices=[('80mm', 'Térmica 80mm'), ('58mm', 'Térmica 58mm'), ('pdf', 'PDF / A4')], default='80mm', max_length=5)),
                ('copias', models.PositiveIntegerField(default=1)),
                ('mostrar_logo', models.BooleanField(default=True)),
                ('mostrar_nit', models.BooleanField(default=True)),
                ('mensaje_pie', models.CharField(blank=True, help_text='Ej: "¡Gracias por su compra! Vuelva pronto."', max_length=200)),
                ('nombre_dispositivo', models.CharField(blank=True, help_text='Nombre exacto de la impresora en el sistema operativo.', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_impresion', to='tiendas.tienda')),
            ],
            options={
                'db_table': 'config_impresion',
            },
        ),
        migrations.CreateModel(
            name='ConfigTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_simbolo', models.CharField(default='$', max_length=5)),
                ('moneda_codigo', models.CharField(default='USD', max_length=5)),
                ('iva_pct', models.DecimalField(decimal_places=2, default=0, help_text='Tasa de IVA en % (ej: 12.00). 0 = sin IVA.', max_digits=5)),
                ('metodos_pago', models.JSONField(default=list, help_text='Ej: ["efectivo","tarjeta","transferencia","mixto"]')),
                ('habilitar_mayoreo', models.BooleanField(default=False, help_text='Activa precios mayoreo en el POS de esta tienda.')),
                ('abono_minimo_pct', models.DecimalField(decimal_places=2, default=20, help_text='% mínimo del total que el cliente debe abonar al apartar.', max_digits=5)),
                ('dias_max_liquidar', models.PositiveIntegerField(default=30, help_text='Días máximos para liquidar un separado antes de vencer.')),
                ('politica_cancelacion', models.CharField(choices=[('retener', 'Retener abono'), ('devolver', 'Devolver abono')], default='retener', help_text='Qué hacer con el abono si el cliente cancela el separado.', max_length=10)),
                ('dias_alerta_separados', models.PositiveIntegerField(default=3, help_text='Días de anticipación para alertar sobre separados próximos a vencer.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='tiendas.tienda')),
            ],
            options={
                'db_table': 'config_tienda',
            },
        ),
    ]
