# Generated by Django 5.2 on 2026-06-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configtienda',
            name='umbral_mayoreo',
            field=models.PositiveIntegerField(blank=True, help_text='Unidades mínimas para precio mayoreo en esta tienda. Si es null, usa el umbral global de la empresa.', null=True),
        ),
    ]
