# Generated by Django 5.2 on 2026-08-25 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_configtienda_umbral_mayoreo'),
        ('empresas', '0002_empresa_cantidad_mayoreo_empresa_maneja_mayoreo'),
        ('tiendas', '0003_tienda_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='Bearer token de acceso (Meta Cloud API).')),
                ('phone_number_id', models.CharField(help_text='Phone Number ID de Meta.', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Config WhatsApp',
                'db_table': 'whatsapp_config',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.CharField(help_text='Número con código de país, sin +. Ej: 573158618847', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_destinatarios', to='empresas.empresa')),
                ('tiendas', models.ManyToManyField(blank=True, help_text='Tiendas cuyos cierres recibe este número. Vacío = todas.', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Destinatario WhatsApp',
                'db_table': 'whatsapp_destinatario',
            },
        ),
    ]
