# Generated by Django 5.1.7 on 2026-04-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_alter_gasto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='visibilidad',
            field=models.CharField(choices=[('todos', 'Todos'), ('solo_admin', 'Solo Admin')], default='todos', max_length=20),
        ),
    ]
