# Generated by Django 5.1.7 on 2026-04-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_empleado_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('cajero', 'Cajero')], default='cajero', max_length=20),
        ),
    ]
