# Generated by Django 5.2 on 2026-08-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_cantidad_mayoreo_empresa_maneja_mayoreo'),
        ('usuarios', '0005_alter_empleado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('empresa', 'cedula')},
        ),
    ]
