# Generated by Django 5.1.7 on 2026-04-10 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('productos', '0002_alter_categoria_id_alter_inventario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='empresas.empresa'),
        ),
    ]
