# Generated by Django 5.1.7 on 2026-05-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_categoria_empresa_producto_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_mayoreo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Precio al por mayor. Solo aplica si la empresa tiene activado 'maneja_mayoreo'. Se usa cuando la cantidad vendida es >= empresa.cantidad_mayoreo.", max_digits=12, null=True),
        ),
    ]
