# Generated by Django 5.2 on 2026-06-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_inventario_stock_averias'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_minima_mayoreo',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad mínima para aplicar precio mayoreo en este producto. Si es null, usa el valor global de empresa.cantidad_mayoreo.', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_mayoreo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Precio al por mayor. Solo aplica si la empresa tiene activado 'maneja_mayoreo'. Se usa cuando la cantidad vendida es >= cantidad_minima_mayoreo (o empresa.cantidad_mayoreo si no se define aquí).", max_digits=12, null=True),
        ),
    ]
