# Generated by Django 5.2 on 2026-06-30 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_apellido_alter_cliente_cedula_nit_and_more'),
        ('empresas', '0002_empresa_cantidad_mayoreo_empresa_maneja_mayoreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='total_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='TierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('umbral_min', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('umbral_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('color_hex', models.CharField(default='#76777D', max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='empresas.empresa')),
            ],
            options={
                'db_table': 'tier_configs',
                'ordering': ['orden', 'umbral_min'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nombre'), name='tier_nombre_empresa_uniq')],
            },
        ),
    ]
