# Generated by Django 5.2 on 2026-07-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_tier_config_y_acumulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
