# Generated by Django 5.2 on 2026-08-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_movimientocaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('venta', 'Venta'), ('abono_separado', 'Abono separado'), ('abono_credito', 'Abono crédito'), ('gasto', 'Gasto'), ('ingreso_manual', 'Ingreso manual')], max_length=20),
        ),
    ]
