# Generated by Django 5.2 on 2026-08-12 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_alter_movimientocaja_tipo'),
        ('tiendas', '0003_tienda_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sesioncaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('tienda',), name='una_sesion_abierta_por_tienda'),
        ),
    ]
