# Generated by Django 5.2 on 2026-08-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_sesioncaja_una_sesion_abierta_por_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('venta', 'Venta'), ('abono_separado', 'Abono separado'), ('abono_credito', 'Abono crédito'), ('cancelacion_separado', 'Cancelación separado'), ('gasto', 'Gasto'), ('ingreso_manual', 'Ingreso manual')], max_length=20),
        ),
    ]
