# Generated by Django 5.1.7 on 2026-04-10 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('tiendas', '0002_alter_tienda_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to='empresas.empresa'),
        ),
    ]
