# Generated by Django 5.1.7 on 2026-04-15 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0001_initial'),
        ('tiendas', '0003_tienda_empresa'),
        ('ventas', '0003_remove_devolucion_empleado_remove_devolucion_venta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledevolucion',
            name='motivo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='metodo_devolucion',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('nota_credito', 'Nota Crédito')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['tienda', '-created_at'], name='devolucione_tienda__de2a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['venta'], name='devolucione_venta_i_14e02c_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['estado'], name='devolucione_estado_d472b2_idx'),
        ),
    ]
