# Generated by Django 5.1.7 on 2026-04-15 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0002_alter_detalledevolucion_motivo_and_more'),
        ('tiendas', '0003_tienda_empresa'),
        ('ventas', '0003_remove_devolucion_empleado_remove_devolucion_venta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='tipo',
            field=models.CharField(choices=[('devolucion', 'Devolución'), ('cambio', 'Cambio')], default='devolucion', max_length=20),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['tipo'], name='devolucione_tipo_7029a7_idx'),
        ),
    ]
