# Generated by Django 5.1.7 on 2026-04-15 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0003_devolucion_tipo_and_more'),
        ('productos', '0003_categoria_empresa_producto_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='cantidad_reemplazo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='producto_reemplazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_como_reemplazo', to='productos.producto'),
        ),
    ]
