# Generated by Django 5.1.7 on 2026-04-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0004_devolucion_cantidad_reemplazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='cambio_entregado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='diferencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='metodo_pago_diferencia',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('nota_credito', 'Nota Crédito')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='tipo_diferencia',
            field=models.CharField(blank=True, choices=[('exacto', 'Exacto'), ('cobrar', 'Cobrar'), ('devolver', 'Devolver')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='total_reemplazo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
