# Generated by Django 5.1.7 on 2026-04-06 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_categoria_id_alter_inventario_id_and_more'),
        ('proveedores', '0002_alter_compra_id_alter_detallecompra_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='nombre_libre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
