# Generated by Django 5.1.7 on 2026-04-06 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_categoria_id_alter_inventario_id_and_more'),
        ('proveedores', '0003_detallecompra_nombre_libre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_compra', to='productos.categoria'),
        ),
    ]
