# Generated by Django 5.2 on 2026-07-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_proveedor_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='codigo_barras_input',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
