# Generated by Django 5.2 on 2026-07-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_detallecompra_precio_venta_y_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='a_credito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
