# Generated by Django 5.2 on 2026-07-18 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0007_compra_credito_campos'),
        ('tiendas', '0003_tienda_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendas.tienda'),
        ),
        migrations.CreateModel(
            name='DistribucionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='proveedores.detallecompra')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendas.tienda')),
            ],
            options={
                'db_table': 'distribuciones_detalle',
                'unique_together': {('detalle', 'tienda')},
            },
        ),
    ]
