# Generated by Django 5.2 on 2026-08-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_cantidad_mayoreo_empresa_maneja_mayoreo'),
        ('proveedores', '0008_distribucion_multitienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('empresa', 'nit')},
        ),
    ]
