# Generated by Django 5.1.7 on 2026-05-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cantidad_mayoreo',
            field=models.PositiveIntegerField(default=12, help_text='Cantidad mínima de unidades del mismo producto para aplicar el precio mayoreo. Ejemplo: 6 significa que desde 6 unidades en adelante se usa el precio mayoreo.'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='maneja_mayoreo',
            field=models.BooleanField(default=False, help_text='Indica si la empresa maneja precios al por mayor.'),
        ),
    ]
